//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSTSmartScholarship.Business.AccountingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://accounting.bstsmartscholarship.com/", ConfigurationName="AccountingService.AccountingSoap")]
    public interface AccountingSoap {
        
        // CODEGEN: Generating message contract since element name StudentNumber from namespace http://accounting.bstsmartscholarship.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://accounting.bstsmartscholarship.com/RequestRefund", ReplyAction="*")]
        BSTSmartScholarship.Business.AccountingService.RequestRefundResponse RequestRefund(BSTSmartScholarship.Business.AccountingService.RequestRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accounting.bstsmartscholarship.com/RequestRefund", ReplyAction="*")]
        System.Threading.Tasks.Task<BSTSmartScholarship.Business.AccountingService.RequestRefundResponse> RequestRefundAsync(BSTSmartScholarship.Business.AccountingService.RequestRefundRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRefundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestRefund", Namespace="http://accounting.bstsmartscholarship.com/", Order=0)]
        public BSTSmartScholarship.Business.AccountingService.RequestRefundRequestBody Body;
        
        public RequestRefundRequest() {
        }
        
        public RequestRefundRequest(BSTSmartScholarship.Business.AccountingService.RequestRefundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accounting.bstsmartscholarship.com/")]
    public partial class RequestRefundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double reimbursementAmount;
        
        public RequestRefundRequestBody() {
        }
        
        public RequestRefundRequestBody(string StudentNumber, double reimbursementAmount) {
            this.StudentNumber = StudentNumber;
            this.reimbursementAmount = reimbursementAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRefundResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestRefundResponse", Namespace="http://accounting.bstsmartscholarship.com/", Order=0)]
        public BSTSmartScholarship.Business.AccountingService.RequestRefundResponseBody Body;
        
        public RequestRefundResponse() {
        }
        
        public RequestRefundResponse(BSTSmartScholarship.Business.AccountingService.RequestRefundResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accounting.bstsmartscholarship.com/")]
    public partial class RequestRefundResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestRefundResult;
        
        public RequestRefundResponseBody() {
        }
        
        public RequestRefundResponseBody(string RequestRefundResult) {
            this.RequestRefundResult = RequestRefundResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingSoapChannel : BSTSmartScholarship.Business.AccountingService.AccountingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingSoapClient : System.ServiceModel.ClientBase<BSTSmartScholarship.Business.AccountingService.AccountingSoap>, BSTSmartScholarship.Business.AccountingService.AccountingSoap {
        
        public AccountingSoapClient() {
        }
        
        public AccountingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BSTSmartScholarship.Business.AccountingService.RequestRefundResponse BSTSmartScholarship.Business.AccountingService.AccountingSoap.RequestRefund(BSTSmartScholarship.Business.AccountingService.RequestRefundRequest request) {
            return base.Channel.RequestRefund(request);
        }
        
        public string RequestRefund(string StudentNumber, double reimbursementAmount) {
            BSTSmartScholarship.Business.AccountingService.RequestRefundRequest inValue = new BSTSmartScholarship.Business.AccountingService.RequestRefundRequest();
            inValue.Body = new BSTSmartScholarship.Business.AccountingService.RequestRefundRequestBody();
            inValue.Body.StudentNumber = StudentNumber;
            inValue.Body.reimbursementAmount = reimbursementAmount;
            BSTSmartScholarship.Business.AccountingService.RequestRefundResponse retVal = ((BSTSmartScholarship.Business.AccountingService.AccountingSoap)(this)).RequestRefund(inValue);
            return retVal.Body.RequestRefundResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BSTSmartScholarship.Business.AccountingService.RequestRefundResponse> BSTSmartScholarship.Business.AccountingService.AccountingSoap.RequestRefundAsync(BSTSmartScholarship.Business.AccountingService.RequestRefundRequest request) {
            return base.Channel.RequestRefundAsync(request);
        }
        
        public System.Threading.Tasks.Task<BSTSmartScholarship.Business.AccountingService.RequestRefundResponse> RequestRefundAsync(string StudentNumber, double reimbursementAmount) {
            BSTSmartScholarship.Business.AccountingService.RequestRefundRequest inValue = new BSTSmartScholarship.Business.AccountingService.RequestRefundRequest();
            inValue.Body = new BSTSmartScholarship.Business.AccountingService.RequestRefundRequestBody();
            inValue.Body.StudentNumber = StudentNumber;
            inValue.Body.reimbursementAmount = reimbursementAmount;
            return ((BSTSmartScholarship.Business.AccountingService.AccountingSoap)(this)).RequestRefundAsync(inValue);
        }
    }
}
