// <auto-generated />
namespace BSTSmartScholarship.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Updates_Misc_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates_Misc_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201211261817268_Updates_Misc_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
