// <auto-generated />
namespace BSTSmartScholarship.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_AwardedAmount_To_Award : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AwardedAmount_To_Award));
        
        string IMigrationMetadata.Id
        {
            get { return "201212070315406_Add_AwardedAmount_To_Award"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
