// <auto-generated />
namespace BSTSmartScholarship.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_IsVerified_For_Applicant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsVerified_For_Applicant));
        
        string IMigrationMetadata.Id
        {
            get { return "201211220311095_Add_IsVerified_For_Applicant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
